//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinCataLogAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XinComic
    {
        public int Id { get; set; }
        public string Series { get; set; }
        public string Title { get; set; }
        public int Number { get; set; }
    }
}
